[target.thumbv7em-none-eabihf]
# Minimal config for embedded Rust
rustflags = [
  # Link script from cortex-m-rt
  "-C", "link-arg=-Tlink.x",
]

[build]
# Set default target so you don't need to specify it every time
target = "thumbv7em-none-eabihf"

[profile.dev]
panic = "abort"
debug = true
opt-level = "s"  # Optimize for size

[profile.release]
panic = "abort"
debug = true
lto = true
opt-level = "s"  # Optimize for size